name: Publish to nuget
on:
  workflow_dispatch:
  push:
    branches:
      - master # Default release branch
jobs:
  publish:
    name: Build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build projects
        run: dotnet build -c Release

      - name: Pack projects
        run: dotnet pack --include-symbols -p:SymbolPackageFormat=snupkg --no-build -c Release -o .

      - name: Push projects
        run: dotnet nuget push **/*.nupkg -k ${{secrets.NUGET_API_KEY}} --skip-duplicate